### ISSUE TITLE
Excuse me, https://grants.protocol.ai/ prompts that the https certificate is invalid.

### ISSUE THREAD

**Issue by gitsrc** [protocol/research-RFPs#27]
Excuse me, https://grants.protocol.ai/ prompts that the https certificate is invalid.

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/34047788/187162152-79e57491-021c-4c20-9dc2-b365dbe6528a.png">

**Comment by asilinphoto** [comment]
Hi @gitsrc we are actively working on resolving this issue! In the meantime, you may access the grants portal through https://protocollabs.smapply.io/

**Comment by gitsrc** [comment]
> Hi @gitsrc we are actively working on resolving this issue! In the meantime, you may access the grants portal through https://protocollabs.smapply.io/

Ok, thanks a lot.
