### ISSUE TITLE
RFP - 6: Smart Contracts on IPFS

### ISSUE THREAD

**Issue by ghiliweld** [protocol/research-RFPs#6]
Not exactly sure how we can apply for a grant but I'd like to present something I've been researching for a while.

I started researching a concept I call "e-contracts", which is an idea that leverages IPFS to emulate smart contract behavior off-chain similarly to a DAG, including timestamps for user data and updates to control ordering of events. So not only do we have decentralized storage off-chain but we can now have **programmable** and **trustless** stores on IPFS.

If Protocol Labs is willing to fund research like this can someone contact me by email?
My email is ghiliaweld@gmail.com

**Comment by miyazono** [comment]
Conversation moved to email.  Problems should be proposed in [protocol/research](https://github.com/protocol/research/issues), or in project repos (like IPFS [notes](https://github.com/ipfs/notes/issues)), and submissions should be sent using the [RFP application instructions](https://github.com/protocol/research-RFPs/blob/master/RFP-application-instructions.md)
